update .visualization generator script for new paths

diff --git a/bin/scc b/bin/scc
--- a/bin/scc
+++ b/bin/scc
@@ -37,17 +37,19 @@ echo
 echo
 
 
-cd $BIN/../../compiler  #project
+cd $BIN/../ftl  #project
 #echo "# cd'ing to FTL root, `pwd`"
 #echo "# Running FTL compiler: ./bin/runFtlWebCLfast $GRAMMAR $TMP"
 echo -e "\e[33m########################################"
 echo "#        Running FTL compiler          #"
 echo -e "########################################\e[0m"
-exec 3>&1 4>&2
-FTLOUTPUT=$({ `./bin/runFtlWebCLfast $EXPANDED $TMP` 2>&4 | grep -v -F 'BUILD SUCCESSFUL' 1>&3;} 4>&1) # 3>/dev/null (redirects stdout of ant to /dev/null)
-exec 3>&- 4>&-
+# exec 3>&1 4>&2
+# FTLOUTPUT=$({ `./runFtlWebCLfast $EXPANDED $TMP` 2>&4 | grep -v -F 'BUILD SUCCESSFUL' 1>&3;} 4>&1) # 3>/dev/null (redirects stdout of ant to /dev/null)
+echo "Running ./runFtlWebCLfast $EXPANDED $TMP"
+./runFtlWebCLfast $EXPANDED $TMP
+# exec 3>&- 4>&-
 
-if [ -n "$FTLOUTPUT" ]; then echo -e "\n\e[1;31mError compiling FTL file\e[0m" >&2; exit 1; fi
+# if [ -n "$FTLOUTPUT" ]; then echo -e "\n\e[1;31mError compiling FTL file\e[0m" >&2; exit 1; fi
 echo
 echo
 
